// breeds.js — Breed Explorer reference data. This is genuinely static,
// evergreen content (breed history/temperament/health characteristics
// don't change week to week the way news or prices do), written from
// general knowledge rather than fetched or fabricated. Popularity is given
// as a qualitative tier rather than an invented specific ranking/number,
// since exact current rankings vary by registry and weren't verified
// against a live source.

export const BREEDS = [
  {
    slug: 'abyssinian', name: 'Abyssinian', emoji: '🐆',
    origin: 'Believed to have roots near the Indian Ocean coast/Southeast Asia, popularized in Britain in the 1800s under the name "Abyssinian."',
    coatLength: 'short', energyLevel: 5, careDifficulty: 2, friendliness: 4,
    personality: 'Energetic, curious, and highly playful — an Aby wants to climb, explore, and be wherever you are.',
    health: 'Generally healthy; some lines carry a higher risk of a hereditary retinal condition and gingivitis, so regular vet checks help.',
    related: ['somali', 'ocicat'],
  },
  {
    slug: 'american-shorthair', name: 'American Shorthair', emoji: '🐈',
    origin: 'Descended from working cats brought to North America by early settlers; recognized as a distinct breed in the early 1900s.',
    coatLength: 'short', energyLevel: 3, careDifficulty: 1, friendliness: 4,
    personality: 'Easygoing, adaptable, and low-drama — a sturdy, sociable companion that gets along with most households.',
    health: 'One of the hardier breeds overall, with no major breed-specific concerns beyond routine weight management.',
    related: ['british-shorthair', 'domestic-shorthair'],
  },
  {
    slug: 'bengal', name: 'Bengal', emoji: '🐅',
    origin: 'Developed in the mid-1900s by crossing domestic cats with the Asian leopard cat, aiming for a wild look with a domestic temperament.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 3, friendliness: 3,
    personality: 'Athletic and intense — Bengals love to jump, climb, and often enjoy water more than most cats.',
    health: 'Generally robust; some lines are screened for a heart condition (hypertrophic cardiomyopathy) common across many breeds.',
    related: ['egyptian-mau', 'ocicat'],
  },
  {
    slug: 'birman', name: 'Birman', emoji: '🐾',
    origin: 'Associated with legends of sacred temple cats in Myanmar; developed as a breed in France in the early 1900s.',
    coatLength: 'medium', energyLevel: 2, careDifficulty: 2, friendliness: 5,
    personality: 'Gentle and affectionate, with a calm, steady presence — Birmans are known for their striking blue eyes and white "gloved" paws.',
    health: 'Generally healthy; routine screening for heart conditions is recommended, as with most pedigreed breeds.',
    related: ['ragdoll', 'siamese'],
  },
  {
    slug: 'british-shorthair', name: 'British Shorthair', emoji: '🐱',
    origin: 'Descended from Roman-era domestic cats in Britain; formalized as a show breed in the late 1800s.',
    coatLength: 'short', energyLevel: 2, careDifficulty: 1, friendliness: 4,
    personality: 'Calm, dignified, and easygoing — the round-faced "teddy bear" look matches a mellow, undemanding temperament.',
    health: 'Prone to weight gain if overfed; otherwise a sturdy breed with a long typical lifespan.',
    related: ['exotic-shorthair', 'chartreux'],
  },
  {
    slug: 'burmese', name: 'Burmese', emoji: '🟤',
    origin: 'Traced to a single brown cat brought from Burma (Myanmar) to the US in the 1930s, then developed further in America and Britain.',
    coatLength: 'short', energyLevel: 4, careDifficulty: 1, friendliness: 5,
    personality: 'Sociable and people-oriented, often described as dog-like in how closely they follow their favorite humans.',
    health: 'Some lines are prone to a facial conformation issue and diabetes risk; reputable breeders screen for both.',
    related: ['tonkinese', 'siamese'],
  },
  {
    slug: 'chartreux', name: 'Chartreux', emoji: '🩶',
    origin: 'An old French breed, historically associated with monasteries, known for its dense blue-grey coat.',
    coatLength: 'short', energyLevel: 2, careDifficulty: 1, friendliness: 4,
    personality: 'Quiet and observant, often called a "smiling cat" for its resting expression — calm but playful in short bursts.',
    health: 'Generally robust and long-lived, with no major breed-specific health concerns.',
    related: ['british-shorthair', 'russian-blue'],
  },
  {
    slug: 'cornish-rex', name: 'Cornish Rex', emoji: '🌀',
    origin: 'Originated from a curly-coated kitten born in Cornwall, England, in 1950, bred selectively from there.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 2, friendliness: 4,
    personality: 'Extremely playful and warm to the touch (thanks to a thin, wavy coat with no guard hairs) — often active well into adulthood.',
    health: 'Thin coat means more sensitivity to cold and sun; otherwise generally healthy.',
    related: ['devon-rex', 'sphynx'],
  },
  {
    slug: 'devon-rex', name: 'Devon Rex', emoji: '🦇',
    origin: 'Discovered in Devon, England, in the 1960s from a spontaneous curly-coat mutation, unrelated to the Cornish Rex despite the similar name.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 2, friendliness: 5,
    personality: 'Mischievous, people-focused, and famously described as "pixie-like" — large ears, big eyes, and an appetite for mischief.',
    health: 'Skin can be more sensitive; some lines carry a hereditary muscle condition, so screening is worthwhile.',
    related: ['cornish-rex', 'sphynx'],
  },
  {
    slug: 'domestic-shorthair', name: 'Domestic Shorthair (Mixed)', emoji: '😺',
    origin: 'Not a formal pedigreed breed — simply the mixed-ancestry cats that make up most of the world\'s pet cat population.',
    coatLength: 'short', energyLevel: 3, careDifficulty: 1, friendliness: 4,
    personality: 'As varied as people — mixed-breed cats span the full range of personalities, and shelters are full of wonderful ones.',
    health: 'Often benefits from greater genetic diversity than pedigreed breeds, though individual health always varies.',
    related: ['american-shorthair'],
  },
  {
    slug: 'egyptian-mau', name: 'Egyptian Mau', emoji: '🐆',
    origin: 'One of the older natural spotted breeds, with a lineage often traced back to ancient Egypt and refined as a breed in the mid-1900s.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 2, friendliness: 3,
    personality: 'Fast, athletic, and famously one of the quickest domestic cat breeds — devoted to their people but wary of strangers.',
    health: 'Generally healthy, with routine heart screening recommended as with most breeds.',
    related: ['bengal', 'ocicat'],
  },
  {
    slug: 'exotic-shorthair', name: 'Exotic Shorthair', emoji: '🐹',
    origin: 'Developed in the 1960s by crossing Persians with shorthair breeds, aiming for the Persian look with easier grooming.',
    coatLength: 'short', energyLevel: 2, careDifficulty: 2, friendliness: 4,
    personality: 'Sweet, quiet, and low-key — nicknamed the "lazy man\'s Persian" for a similar temperament with less brushing.',
    health: 'Shares the Persian\'s flat-faced conformation, which can bring breathing and eye-tearing issues; look for breeders prioritizing health.',
    related: ['persian', 'british-shorthair'],
  },
  {
    slug: 'maine-coon', name: 'Maine Coon', emoji: '🦁',
    origin: 'A native New England breed with murky folklore origins, valued historically as a hardy farm and ship cat.',
    coatLength: 'long', energyLevel: 3, careDifficulty: 3, friendliness: 5,
    personality: 'A gentle giant — large, dog-like in loyalty, sociable, and often surprisingly chirpy-voiced for such a big cat.',
    health: 'Prone to hip dysplasia and a heart condition (hypertrophic cardiomyopathy) in some lines; screening is standard practice.',
    related: ['norwegian-forest-cat', 'ragdoll'],
  },
  {
    slug: 'manx', name: 'Manx', emoji: '🐇',
    origin: 'Originates from the Isle of Man, where a natural genetic mutation produces cats with short or absent tails.',
    coatLength: 'short', energyLevel: 3, careDifficulty: 1, friendliness: 4,
    personality: 'Loyal and playful, often forming a strong bond with one person or family; known for a distinctive rounded, tailless silhouette.',
    health: 'The tailless gene can be linked to spinal issues in some cats ("Manx syndrome"); responsible breeding screens against this.',
    related: ['american-shorthair'],
  },
  {
    slug: 'norwegian-forest-cat', name: 'Norwegian Forest Cat', emoji: '🌲',
    origin: 'A natural breed from Norway, adapted over centuries to a cold climate, with roots possibly tracing back to cats brought by early seafarers.',
    coatLength: 'long', energyLevel: 3, careDifficulty: 3, friendliness: 4,
    personality: 'Calm, independent, and a skilled climber — a sturdy, weatherproof coat and tufted paws give it a wild, forest-cat look.',
    health: 'Some lines are screened for a heart condition and a glycogen storage disease; otherwise a hardy breed.',
    related: ['maine-coon', 'siberian'],
  },
  {
    slug: 'ocicat', name: 'Ocicat', emoji: '🐯',
    origin: 'Developed in the US in the 1960s from Siamese and Abyssinian crosses, bred to look spotted like a wild cat despite being fully domestic.',
    coatLength: 'short', energyLevel: 4, careDifficulty: 1, friendliness: 5,
    personality: 'Outgoing and trainable — often described as dog-like, some Ocicats can learn to walk on a leash or play fetch.',
    health: 'Generally healthy, with no major breed-specific concerns.',
    related: ['bengal', 'egyptian-mau'],
  },
  {
    slug: 'persian', name: 'Persian', emoji: '🐈‍⬛',
    origin: 'One of the oldest known breeds, with long-haired cats from the Persia/Iran region documented in Europe as early as the 1600s.',
    coatLength: 'long', energyLevel: 1, careDifficulty: 5, friendliness: 4,
    personality: 'Calm, quiet, and affectionate in a low-key way — happiest in a peaceful home, content to lounge nearby.',
    health: 'The flat-faced conformation common in modern lines can bring breathing difficulty and eye tearing; the long coat needs daily brushing to avoid matting.',
    related: ['exotic-shorthair', 'himalayan'],
  },
  {
    slug: 'ragdoll', name: 'Ragdoll', emoji: '🧸',
    origin: 'Developed in California in the 1960s, bred specifically for a docile, relaxed temperament alongside its striking color-point coat.',
    coatLength: 'long', energyLevel: 2, careDifficulty: 3, friendliness: 5,
    personality: 'Famously floppy and relaxed — many Ragdolls go limp when picked up, and they tend to be very people-oriented.',
    health: 'Screened for a heart condition (hypertrophic cardiomyopathy) in reputable lines; otherwise generally healthy.',
    related: ['birman', 'maine-coon'],
  },
  {
    slug: 'russian-blue', name: 'Russian Blue', emoji: '🩵',
    origin: 'Believed to originate near Arkhangelsk, Russia, brought to Western Europe by sailors in the 1800s.',
    coatLength: 'short', energyLevel: 3, careDifficulty: 1, friendliness: 3,
    personality: 'Reserved with strangers but deeply loyal to their people, with a dense silvery-blue coat and a quiet, gentle demeanor.',
    health: 'One of the hardier breeds, with a reputation for a long, healthy lifespan.',
    related: ['chartreux', 'british-shorthair'],
  },
  {
    slug: 'scottish-fold', name: 'Scottish Fold', emoji: '🙉',
    origin: 'Traced to a single folded-ear barn cat found in Scotland in 1961, a spontaneous genetic mutation affecting cartilage.',
    coatLength: 'short', energyLevel: 3, careDifficulty: 2, friendliness: 5,
    personality: 'Sweet-natured and adaptable, known for an owl-like round face and folded ears that give a distinctive, endearing look.',
    health: 'The same cartilage mutation that folds the ears can cause painful joint and bone issues (osteochondrodysplasia); this is a real animal-welfare concern potential owners should research carefully.',
    related: ['british-shorthair', 'american-curl'],
  },
  {
    slug: 'siamese', name: 'Siamese', emoji: '💎',
    origin: 'One of the oldest recognized Asian breeds, originating in Siam (modern Thailand) and documented for centuries before reaching the West in the 1800s.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 1, friendliness: 5,
    personality: 'Vocal, social, and highly intelligent — Siamese cats form intense bonds with their people and are rarely quiet about what they want.',
    health: 'Some lines carry a higher risk of dental issues and a heart condition; otherwise a hardy, long-lived breed.',
    related: ['oriental-shorthair', 'burmese'],
  },
  {
    slug: 'sphynx', name: 'Sphynx', emoji: '👽',
    origin: 'Developed in Canada in the 1960s from a naturally occurring hairless mutation, bred selectively from there.',
    coatLength: 'hairless', energyLevel: 4, careDifficulty: 4, friendliness: 5,
    personality: 'Extremely affectionate and attention-seeking — warm to the touch and often described as more "in your business" than most cats.',
    health: 'No fur means more sensitivity to sun and cold, and regular bathing is needed to manage skin oils that a coat would normally absorb.',
    related: ['devon-rex', 'cornish-rex'],
  },
  {
    slug: 'turkish-van', name: 'Turkish Van', emoji: '🏊',
    origin: 'A natural breed from the Lake Van region of Turkey, historically noted for an unusual comfort around water.',
    coatLength: 'medium', energyLevel: 5, careDifficulty: 2, friendliness: 3,
    personality: 'Energetic and independent, with a reputation — not universal, but well documented — for actually enjoying a swim.',
    health: 'Generally healthy and hardy, with a water-resistant coat that sheds dirt easily.',
    related: ['turkish-angora'],
  },
  {
    slug: 'turkish-angora', name: 'Turkish Angora', emoji: '🕊️',
    origin: 'An ancient natural breed from the Ankara region of Turkey, among the first long-haired cats known in Europe.',
    coatLength: 'long', energyLevel: 4, careDifficulty: 2, friendliness: 4,
    personality: 'Playful, intelligent, and elegant, with a fine silky coat that mats less than other long-haired breeds.',
    health: 'White Angoras with blue eyes have a higher-documented rate of congenital deafness; otherwise generally healthy.',
    related: ['turkish-van', 'persian'],
  },
  {
    slug: 'somali', name: 'Somali', emoji: '🦊',
    origin: 'Essentially a long-haired Abyssinian, first appearing spontaneously in Aby litters and developed as its own breed from the 1960s onward.',
    coatLength: 'medium', energyLevel: 5, careDifficulty: 3, friendliness: 4,
    personality: 'Fox-like in looks and just as clever — active, curious, and known for a bushy tail and ticked coat.',
    health: 'Shares similar considerations to the Abyssinian, including a hereditary retinal condition in some lines.',
    related: ['abyssinian'],
  },
  {
    slug: 'tonkinese', name: 'Tonkinese', emoji: '🐟',
    origin: 'Developed by crossing Siamese and Burmese cats, aiming to blend traits of both — first standardized in Canada in the mid-1900s.',
    coatLength: 'short', energyLevel: 4, careDifficulty: 1, friendliness: 5,
    personality: 'Social and people-focused, often landing temperamentally between the vocal Siamese and the mellower Burmese.',
    health: 'Generally healthy; inherits similar considerations to its Siamese and Burmese ancestry.',
    related: ['siamese', 'burmese'],
  },
  {
    slug: 'himalayan', name: 'Himalayan', emoji: '🏔️',
    origin: 'Developed by crossing Persians with Siamese to bring color-point patterning to the Persian\'s long coat, standardized by the mid-1900s.',
    coatLength: 'long', energyLevel: 1, careDifficulty: 5, friendliness: 4,
    personality: 'Gentle and placid like the Persian, with the striking blue eyes and color points of its Siamese ancestry.',
    health: 'Shares the Persian\'s flat-faced conformation concerns; daily grooming is needed for the long coat.',
    related: ['persian', 'siamese'],
  },
  {
    slug: 'siberian', name: 'Siberian', emoji: '❄️',
    origin: 'A natural, centuries-old landrace breed from Russia, bred by climate rather than by breeders until formal recognition in the late 1900s.',
    coatLength: 'long', energyLevel: 4, careDifficulty: 3, friendliness: 5,
    personality: 'Powerful, agile, and affectionate — a hardy triple coat suited to cold climates, often good with families.',
    health: 'Generally robust; often anecdotally reported as more tolerable for some cat-allergy sufferers, though this varies by individual.',
    related: ['norwegian-forest-cat', 'maine-coon'],
  },
  {
    slug: 'american-curl', name: 'American Curl', emoji: '👂',
    origin: 'Traced to a single stray kitten with unusual curled ears found in California in 1981, a spontaneous genetic mutation.',
    coatLength: 'medium', energyLevel: 3, careDifficulty: 2, friendliness: 5,
    personality: 'Affectionate and adaptable, best known for ears that curl backward — kittens are born with straight ears that curl within about a week.',
    health: 'The ear cartilage is softer than average, so cleaning must be gentle; otherwise a healthy breed.',
    related: ['scottish-fold'],
  },
  {
    slug: 'oriental-shorthair', name: 'Oriental Shorthair', emoji: '🦋',
    origin: 'Developed from Siamese lines in Britain in the mid-1900s, bred to explore the full range of coat colors and patterns on the same sleek body type.',
    coatLength: 'short', energyLevel: 5, careDifficulty: 1, friendliness: 5,
    personality: 'Vocal, social, and intelligent, sharing the Siamese\'s chatty, people-oriented temperament across a much wider palette of colors.',
    health: 'Similar considerations to the Siamese, including a somewhat higher risk of dental and heart issues in some lines.',
    related: ['siamese'],
  },
];

export function getBreed(slug) {
  return BREEDS.find(b => b.slug === slug) || null;
}

export function relatedBreedsFor(slug) {
  const breed = getBreed(slug);
  if (!breed) return [];
  return breed.related.map(getBreed).filter(Boolean);
}
